
name: Generate and lint code

on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: './go.mod'
    - name: Verify Patches
      run: make patch-all
    - name: Generate
      run: |
        make generate-all
        # Expect all changes to be accounted for
        ! git status --porcelain | grep .
    - name: Determine golangci-lint version
      id: golangcilint
      run: |
        line=$(grep GOLANGCI_LINT_VERSION= Makefile)
        version=$(echo ${line} | cut -d = -f2)
        echo "version=$version" >> "$GITHUB_OUTPUT"
    - name: Lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: ${{ steps.golangcilint.outputs.version }}
        skip-cache: true
    - name: Report tests check
      # When this job is triggered with the automatic
      # GitHub Actions token, we have to explicitly set
      # the commit status
      if: ${{ always() && github.event_name == 'workflow_dispatch' && github.actor == 'github-actions' }}
      uses: myrotvorets/set-commit-status-action@v2.0.1
      with:
        context: test # This must be hard-coded to match the job name
        status: ${{ job.status }}
        sha: ${{ github.sha }}
