name: "Validate PR Title"

on:
  workflow_dispatch:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: write
  statuses: write

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - name: Manually set Actions check
        # action-semantic-pull-request doesn't accept an
        # explicit PR number so for automated jobs we always
        # mark the status as succeeded
        if: ${{ github.event_name == 'workflow_dispatch' && github.actor == 'github-actions[bot]' }}
        uses: myrotvorets/set-commit-status-action@v2.0.1
        with:
          context: Validate PR title # This must be hard-coded to match the job name
          status: "success"
          sha: ${{ github.sha }}
      - uses: amannn/action-semantic-pull-request@v5
        if: ${{ github.event_name != 'workflow_dispatch' }}
        id: lint_pr_title
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: marocchino/sticky-pull-request-comment@v2
        # When the previous steps fails, the workflow would stop. By adding this
        # condition you can continue the execution with the populated error message.
        if: always() && github.event_name != 'workflow_dispatch' && (steps.lint_pr_title.outputs.error_message != null)
        with:
          header: pr-title-lint-error
          message: |
            Hey there and thank you for opening this pull request! 👋🏼

            We require pull request titles to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/) and it looks like your proposed title needs to be adjusted.

            Details:

            ```
            ${{ steps.lint_pr_title.outputs.error_message }}
            ```

      # Delete a previous comment when the issue has been resolved
      - if: ${{ github.event_name != 'workflow_dispatch' && steps.lint_pr_title.outputs.error_message == null }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr-title-lint-error
          delete: true
